#!/bin/bash
set -e
ROOT_UID=0
THEME_DIR="/boot/grub/themes"
THEME_NAME=hamonikr

# Check command avalibility
function has_command() {
  command -v $1 > /dev/null
}
echo -e "\n\t*****************************\n\t*  ${THEME_NAME} - Grub2 Theme  *\n\t*****************************"

# https://en.wikipedia.org/wiki/Display_resolution
RES=`xrandr --current | grep "*" | head -n 1 | awk -F" " '{print $1}'`
WIDTH=`xrandr --current | grep "*" | head -n 1 | awk -F" " '{print $1}' | awk -F"x" '{print $1}'`
if [ ! -z "$WIDTH" ] ; then
  # Foced adjust for HIDPI Resolution
  if [ "$WIDTH" -gt "1920" ] ; then
    # echo "HIDPI"
    sed -i.bak "s/.*GRUB_GFXMODE.*/GRUB_GFXMODE=1920x1080/g" /etc/default/grub
  else
    # echo "NORMAL"  
    sed -i.bak "s/.*GRUB_GFXMODE.*/GRUB_GFXMODE=${RES}/g" /etc/default/grub
  fi
fi

# for hamonikr os  
if [[ -f "/etc/hamonikr/info" ]] ; then
  if [ -x "/etc/hamonikr/adjustments/10-adjust-grub-title.execute" ] ; then
    /etc/hamonikr/adjustments/10-adjust-grub-title.execute
  else
    echo "Found HamoniKR OS Infomation"
    OSNAME=$( sed -n '/GRUB_TITLE=/p' /etc/hamonikr/info | cut -d'=' -f2 | sed 's/"//g' ) >/dev/null 2>&1
    sed -i.bak '/GRUB_DISTRIBUTOR=/d' /etc/default/grub >/dev/null 2>&1
    echo "GRUB_DISTRIBUTOR=\"${OSNAME}\"" >> /etc/default/grub
  fi
fi

if [ -f "/etc/default/grub" ] ; then
  # Set theme
  echo -e "Setting ${THEME_NAME} as default..."

  # sed -i.bak '/GRUB_CMDLINE_LINUX_DEFAULT=/d' /etc/default/grub >/dev/null 2>&1
  # echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash LANG=ko_KR\"" >> /etc/default/grub   

  grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i.bak '/GRUB_THEME=/d' /etc/default/grub
  [[ -d /boot/grub ]] && echo "GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"" >> /etc/default/grub  

  sed -i.bak '/GRUB_TIMEOUT=/d' /etc/default/grub >/dev/null 2>&1
  echo "GRUB_TIMEOUT=5" >> /etc/default/grub 
fi

## Support LDME and debian bullseye
if [ ! -f "/etc/hamonikr/.bak/os-release.bak" ]; then
  CODENAME=$(lsb_release -c -s)
  if [ "X${CODENAME}" == "Xelsie" ] ||  [ "X${CODENAME}" == "Xbullseye" ] ; then
    echo "#! /bin/sh" > /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "set -e" >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo ""  >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "GRUB_THEME=\"/boot/grub/themes/hamonikr/theme.txt\""  >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "GRUB_TIMEOUT=5"  >> /etc/default/grub.d/90_hamonikr-theme.cfg
  fi
else
  CODENAME=$(cat /etc/hamonikr/.bak/os-release.bak | grep VERSION_CODENAME | cut -d= -f2 )
  if [ "X${CODENAME}" == "Xelsie" ] ||  [ "X${CODENAME}" == "Xbullseye" ] ; then
    echo "#! /bin/sh" > /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "set -e" >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo ""  >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "GRUB_THEME=\"/boot/grub/themes/hamonikr/theme.txt\""  >> /etc/default/grub.d/90_hamonikr-theme.cfg
    echo "GRUB_TIMEOUT=5"  >> /etc/default/grub.d/90_hamonikr-theme.cfg
  fi
fi

# Update grub config
echo -e "Updating grub config..."
if has_command update-grub; then
    update-grub
elif has_command grub-mkconfig; then
    grub-mkconfig -o /boot/grub/grub.cfg
fi

if which systemctl >/dev/null 2>&1
then
    if [ $(systemctl is-enabled hamonikr-system) = "disabled" ] ; then
      systemctl enable hamonikr-system.service
      systemctl daemon-reload
    fi
fi

# Success message
echo -e "\n\t*****************************\n\t*  Installation complete.  *\n\t*****************************"    
exit 0